export type Book = {
  title: string
  price: number
  discountedPrice: number
  checked: boolean
  count: number
}

export const paid: Book[] = [
  { title: "두 개의 바빌론", price: 17000, discountedPrice: 15000, count: 0, checked: false, },
  { title: "고통과 함께 하는 삶", price: 3500, discountedPrice: 3000 , count: 0, checked: false, },
  { title: "우리는 십자가에 못박힌 채 태어났다", price: 8000, discountedPrice: 5000 , count: 0, checked: false, },
  { title: "성령의 열매", price: 12000, discountedPrice: 10000 , count: 0, checked: false, },
  { title: "확실한 기초", price: 8000, discountedPrice: 6000 , count: 0, checked: false, },
  { title: "성장을 위한 첫걸음", price: 15000, discountedPrice: 12000 , count: 0, checked: false, },
  { title: "성경적 종말론", price: 8000, discountedPrice: 6000 , count: 0, checked: false, }, 
  { title: "성경 연구 방법", price: 8000, discountedPrice: 6000 , count: 0, checked: false, },
  { title: "설교의 준비와 전달", price: 4000, discountedPrice: 3000 , count: 0, checked: false, },
  { title: "하늘나라와 지옥", price: 8000, discountedPrice: 6000 , count: 0, checked: false, },
  { title: "쉬운 복음 쉬운 전도", price: 5000, discountedPrice: 4000 , count: 0, checked: false, },
  { title: "교회에 관한 교리", price: 15000, discountedPrice: 12000 , count: 0, checked: false, },
  { title: "창세기 1:1-3강해(간극이론)", price: 4000, discountedPrice: 3000 , count: 0, checked: false, },
  { title: "교회와 대환난", price: 4000, discountedPrice: 3000 , count: 0, checked: false, },
  { title: "세대주의 재고찰", price: 12000, discountedPrice: 10000 , count: 0, checked: false, },
  { title: "구원의 영원한 보장", price: 5000, discountedPrice: 4000 , count: 0, checked: false, },
  { title: "올라가는 기도 내려오는 응답", price: 7000, discountedPrice: 5000 , count: 0, checked: false, },
  { title: "신약 생활 원리", price: 4000, discountedPrice: 3000 , count: 0, checked: false, },
  { title: "성경의 기초들", price: 4000, discountedPrice: 3000 , count: 0, checked: false, },
  { title: "결혼과 가정", price: 10000, discountedPrice: 8000 , count: 0, checked: false, },
  { title: "구원의 조건", price: 4000, discountedPrice: 3000 , count: 0, checked: false, },
  { title: "예수님과 성경", price: 4000, discountedPrice: 3000 , count: 0, checked: false, },
  { title: "히브리서 연구", price: 12000, discountedPrice: 10000 , count: 0, checked: false, }, 
  { title: "창세기 주석", price: 18000, discountedPrice: 15000 , count: 0, checked: false, },
  { title: "그분의 기쁨을 위하여", price: 6000, discountedPrice: 4000 , count: 0, checked: false, }, 
  { title: "하나님의 모든 계획", price: 8000, discountedPrice: 6000 , count: 0, checked: false, },
  { title: "영원히 살려면", price: 4000, discountedPrice: 3000 , count: 0, checked: false, },
  { title: "그리스도인이여, 반드시 알아야 합니다", price: 8000, discountedPrice: 6000 , count: 0, checked: false, },
  { title: "예수그리스도의 인성", price: 8000, discountedPrice: 6000 , count: 0, checked: false, },
  { title: "간극은 있다", price: 15000, discountedPrice: 12000 , count: 0, checked: false, },
  { title: "욥기 연구", price: 13000, discountedPrice: 11000 , count: 0, checked: false, },
  { title: "성경과 지질학", price: 10000, discountedPrice: 8000 , count: 0, checked: false, },
  { title: "로마서 강해", price: 13000, discountedPrice: 11000 , count: 0, checked: false, },
  { title: "영어성경의 감추어진 역사", price: 6000, discountedPrice: 5000 , count: 0, checked: false, },
  { title: "성경은 음악에 대해 무엇이라고 말씀하시는가", price: 3000, discountedPrice: 2000 , count: 0, checked: false, },
  { title: "깨어진 것들", price: 5000, discountedPrice: 4000 , count: 0, checked: false, },
  { title: "말라기 강해", price: 16000, discountedPrice: 14000 , count: 0, checked: false, },
  { title: "경이로운 성경의 예언과 성취", price: 7000, discountedPrice: 6000 , count: 0, checked: false, },
  { title: "영의 세계", price: 7000, discountedPrice: 6000 , count: 0, checked: false, },
  { title: "칭의에서 성화로", price: 5000, discountedPrice: 4000 , count: 0, checked: false, },
  { title: "순간의 선택이 영원을 좌우한다", price: 8000, discountedPrice: 7000 , count: 0, checked: false, },
  { title: "믿음 사용 설명서", price: 4000, discountedPrice: 3000 , count: 0, checked: false, },
  { title: "솔로몬의 인생 보고서 전도서", price: 14000, discountedPrice: 12000 , count: 0, checked: false, },
  { title: "룻기", price: 5000, discountedPrice: 4000 , count: 0, checked: false, },
  { title: "바울의 기도", price: 7000, discountedPrice: 6000 , count: 0, checked: false, },
  { title: "다윗의 실패", price: 7000, discountedPrice: 6000 , count: 0, checked: false, },
  { title: "광야 이야기", price: 5000, discountedPrice: 4000 , count: 0, checked: false, },
  { title: "금송아지 사건", price: 5000, discountedPrice: 4000 , count: 0, checked: false, },
  { title: "의롭게 사는 법", price: 4000, discountedPrice: 3000 , count: 0, checked: false, },
  { title: "건전한 교리", price: 5000, discountedPrice: 4000 , count: 0, checked: false, },
  { title: "승리의 생활", price: 4000, discountedPrice: 3000 , count: 0, checked: false, },
]

export const free: Book[] = [
  { title: "일곱 교회", price: 1500, discountedPrice: 500, count: 0, checked: false, },
  { title: "기독교의 본질", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "성령 침례", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "성경에서 말씀하시는 방언", price: 1000, discountedPrice: 500, count: 0, checked: false, },   
  { title: "신유와 적그리스도", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "교회의 휴거", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "영원을 준비하는 삶", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "예수님 나의 예수님", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "창세기3장 성경공부개요", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "히브리서11장 성경공부개요", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  // { title: "우리는 왜 킹제임스성경을 믿는가", price: 1000, discountedPrice: 0 , count: 0, checked: false, },
  { title: "큰 흰 왕좌 심판", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "청지기-설교자들을 위한 설교", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "하나님의 뜻", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "모든 것이 합력하여 선을 이룬다", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "킹제임스성경이 하나님의 말씀인지 어떻게 아는가", price: 1000, discountedPrice: 500, count: 0, checked: false, }, 
  { title: "성경과 술", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "그리스도인의 옷차림", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "거룩한 여인", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "다시 태어났습니까?", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "하나님께서는 무엇을 받기 원하시는가", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "그리스도의 몸과 지역교회", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "이교도들은 어떻게 되는가", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "하나님의 말씀", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "가장 큰 명령", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "예수님의 죽음부터 부활까지의 활동들", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "성경이 말씀하시는 교회", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "합당한 섬김", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "The Essence of Christianity", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "하나님인가 맘몬인가?", price:  1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "성경이 말씀하시는 보상", price:  1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "셋째 출생", price:  1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "성경에 기록된 과학적 사실들", price:  1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "두 본성", price:  1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "짐승의 표는 무엇인가?", price:  1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "거리 설교의 유익", price:  1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "레위기 개요", price:  1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "천년왕국", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "두 홍수", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "복음과 구원", price: 0, discountedPrice: 500, count: 0, checked: false, },
  { title: "예수 및 여호와 인가 야호 컨넥션 인가?", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "Dino 박사의 창세기 간극 이론의 비판에 대한 전면 반박", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "간극이냐 아니냐에 대한 창세기 1:1-2의 연구", price: 1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "문제있는 성경", price: 0,  discountedPrice: 500, count: 0, checked: false, },
  { title: "진정한 신앙생활", price: 0,  discountedPrice: 500, count: 0, checked: false, },
  { title: "주님이 구상하셨던 교회의 모습", price: 0,  discountedPrice: 500, count: 0, checked: false, },
  { title: "고난의 목적", price: 0,  discountedPrice: 500, count: 0, checked: false, },
  { title: "사무엘 깁의 욥기", price:  1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "사무엘 깁 설교 1. 성경을 읽는 방법", price:  1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "최고수준의 생활", price:  1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "신앙에 관한 질문", price:  1000, discountedPrice: 500, count: 0, checked: false, },
  { title: "예수님의 이름과 칭호들", price:  1000, discountedPrice: 500, count: 0, checked: false, },
]